backend:
  name: github
  repo: acgd-webdev-workshops/realcottages

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            width: "string"
